name: Publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build ${{ matrix.app }}
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        app: [ mastodon, roon, snapraid ]
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Logging in to ECR stops AWS from rate limiting us
      - name: Login to ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        with:
          registry-type: public
      - uses: actions/checkout@v3
      - name: Build and push image
        run: bash build.sh ${{ matrix.app }}
        shell: bash